version: "3"

services:
    app:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - "./:/app"
        command: python manage.py runserver
    postgres:
        image: postgres:13-alpine
        ports:
            - "5432:5432"
