# Generated by Django 3.1.7 on 2021-02-22 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='currency',
            field=models.CharField(default='USD', max_length=100),
            preserve_default=False,
        ),
    ]
