# Generated by Django 3.1.7 on 2021-02-22 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_wallet_currency'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('user', 'currency')},
        ),
    ]
