# Generated by Django 3.1.7 on 2021-02-28 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_instrument_order_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=21),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='side',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='BUY', max_length=4),
            preserve_default=False,
        ),
    ]
